version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest #主容器，运行命令
    filters:
      branches:
        only: master

    steps:
      - add_ssh_keys:
          fingerprints:
          - "6a:92:9a:dd:46:b1:aa:6a:b0:bc:6e:39:29:22:a9:f1" #设置用户密钥

      - checkout

      # Download and cache dependencies
      - restore_cache: #读取缓存
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: echo "部署开始"

      - save_cache: #保存缓存，提高编译速度
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
          ssh -i ~/.ssh/id_rsa_circleci -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./cricleci-deploy.sh"
     
